
---
- name: Create directory and set permissions
  hosts: all
  become: yes
  tasks:
    - name: Create /opt/demo directory
      ansible.builtin.file:
        path: /opt/demo
        state: directory
        mode: '0755'
